spring:
  data:
    mongodb:
      database: airtickets-audit
      port: 2717
      host: localhost
      uri: mongodb://localhost:2717/airtickets-audit
rabbit:
  queue: amqp-audit

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/