spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airtickets
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/airtickets

server:
  port: 8080

jwt:
  secret: capybaraSecret
  subject: capybaraApplication
  access-exp: 1800000
  refresh-exp: 3600000
