spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airtickets
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/airtickets

server:
  port: 0